import { Inter } from "next/font/google";
import "./globals.css";
import ReduxProvider from "@/store/redux-provider";

const inter = Inter({
  subsets: ["latin"],
});

export const metadata = {
  title: "Kanban Board",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <ReduxProvider> {children}</ReduxProvider>
      </body>
    </html>
  );
}
